services:
  - type: web
    name: websocket-render
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health